config/routes.rb
Rails.application.routes.draw do
  resources :conta
  resources :transferencia
  resources :pessoa_juridicas
  resources :pessoa_fisicas

end

app/models/pessoa_fisica.rb
class PessoaFisica < ActiveRecord::Base
    validates :cpf, presence: true,
                  uniqueness: { case_insensitive: false },
                  numericality: { only_integer: true },
                  length: { is: 11 }


  validates :nome, presence: true,
                   format: { with: /\A[^0-9!@\$%\^&*+_=]+\z/ },
                   length: { in: 2..70 }

  has_many :contas, as: :pessoa
end

app/controllers/pessoa_fisicas_controller.rb
class PessoaFisicasController < ApplicationController
  before_action :set_pessoa_fisica, only: [:show, :edit, :update, :destroy]

  # GET /pessoa_fisicas
  # GET /pessoa_fisicas.json
  def index
    @pessoa_fisicas = PessoaFisica.all
  end

  # GET /pessoa_fisicas/1
  # GET /pessoa_fisicas/1.json
  def show
  end

  # GET /pessoa_fisicas/new
  def new
    @pessoa_fisica = PessoaFisica.new
  end

  # GET /pessoa_fisicas/1/edit
  def edit
  end

  # POST /pessoa_fisicas
  # POST /pessoa_fisicas.json
  def create
    @pessoa_fisica = PessoaFisica.new(pessoa_fisica_params)

    respond_to do |format|
      if @pessoa_fisica.save
        format.html { redirect_to @pessoa_fisica, notice: 'Pessoa fisica was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa_fisica }
      else
        format.html { render :new }
        format.json { render json: @pessoa_fisica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoa_fisicas/1
  # PATCH/PUT /pessoa_fisicas/1.json
  def update
    respond_to do |format|
      if @pessoa_fisica.update(pessoa_fisica_params)
        format.html { redirect_to @pessoa_fisica, notice: 'Pessoa fisica was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa_fisica }
      else
        format.html { render :edit }
        format.json { render json: @pessoa_fisica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoa_fisicas/1
  # DELETE /pessoa_fisicas/1.json
  def destroy
    @pessoa_fisica.destroy
    respond_to do |format|
      format.html { redirect_to pessoa_fisicas_url, notice: 'Pessoa fisica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa_fisica
      @pessoa_fisica = PessoaFisica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_fisica_params
      params.require(:pessoa_fisica).permit(:nome, :cpf, :data_de_nascimento)
    end
end

app/helpers/pessoa_fisicas_helper.rb
module PessoaFisicasHelper
end

app/views/pessoa_fisicas/_form.html.erb
<%= form_for(@pessoa_fisica) do |f| %>
  <% if @pessoa_fisica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa_fisica.errors.count, "error") %> prohibited this pessoa_fisica from being saved:</h2>

      <ul>
      <% @pessoa_fisica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento %><br>
    <%= f.date_select :data_de_nascimento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoa_fisicas/edit.html.erb
<h1>Editing Pessoa Fisica</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa_fisica %> |
<%= link_to 'Back', pessoa_fisicas_path %>

app/views/pessoa_fisicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pessoa Fisicas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Data de nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoa_fisicas.each do |pessoa_fisica| %>
      <tr>
        <td><%= pessoa_fisica.nome %></td>
        <td><%= pessoa_fisica.cpf %></td>
        <td><%= pessoa_fisica.data_de_nascimento %></td>
        <td><%= link_to 'Show', pessoa_fisica %></td>
        <td><%= link_to 'Edit', edit_pessoa_fisica_path(pessoa_fisica) %></td>
        <td><%= link_to 'Destroy', pessoa_fisica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa fisica', new_pessoa_fisica_path %>

app/views/pessoa_fisicas/new.html.erb
<h1>New Pessoa Fisica</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoa_fisicas_path %>

app/views/pessoa_fisicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa_fisica.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @pessoa_fisica.cpf %>
</p>

<p>
  <strong>Data de nascimento:</strong>
  <%= @pessoa_fisica.data_de_nascimento %>
</p>

<%= link_to 'Edit', edit_pessoa_fisica_path(@pessoa_fisica) %> |
<%= link_to 'Back', pessoa_fisicas_path %>