config/routes.rb
Rails.application.routes.draw do
  resources :conta
  resources :transferencia
  resources :pessoa_juridicas
  resources :pessoa_fisicas

end

app/models/conta.rb
class Conta < ActiveRecord::Base
    
  after_initialize :iniciar_saldo, if: :new_record?
  validate :validar_ancestry
  before_update :conta_cancelada_nao_recebe_atividade

  enum situacao: [:cancelado, :ativo, :bloqueado]

  validates :nome, presence: true,
                   uniqueness: true,
                   format: { with: /\A[^0-9ç!@\$%\^&*+_=]+\z/ },
                   length: { in: 2..70 }

  validates :saldo, presence: true,
                    numericality: true

  validates :situacao, presence: true,
                     inclusion: { in: Conta.statuses.keys }

  validates :pessoa, presence: true

  belongs_to :pessoa, polymorphic: true
  has_ancestry

  scope :transacoes, -> { Transacao.where('conta_origem_id = ? || conta_destino_id = ?', self.id, self.id) }

  def iniciar_saldo
    self.saldo = 0
    self.situacao = 'ativo'
  end

  def depositar(valor)
    return self unless valor_valido?(valor)

    self.saldo += valor
    self
  end

  def sacar(valor)
    unless valor <= self.saldo
      self.errors.add(:valor, message: 'deve ser maior ou igual ao saldo.')
      return self
    end

    self.saldo -= valor
    self
  end

  def sacar_estorno(valor)
    return self unless valor_valido?(valor)

    self.saldo -= valor
    self
  end

  def conta_valida?
    if self.situacao == 'cancelado' || self.situacao == 'bloqueado'
      errors.add(:conta, message: 'não podem ser efetuadas transações enquanto a conta estiver cancelada/bloqueada')
      false
    else
      true
    end
  end

  private
    def valor_valido?(valor)
      unless valor > 0
        errors.add(:valor, message: 'deve ser maior que 0.')
        return false
      end

      true
    end

    def validar_ancestry
      return true if ancestry.blank?

      conta_ancestry = Conta.find_by(id: self.ancestry.split('/').last)

      if conta_ancestry.blank?
        errors.add(:conta, message: 'conta ancestral não encontrada.')
        return false
      end

      if conta_ancestry.id == self.id
        errors.add(:conta, message: 'conta ancestral não pode ser a própria conta.')
        return false
      end

      if conta_ancestry.ancestor_ids.include?(self.id)
        errors.add(:conta, message: 'conta ancestral não pode ser sua descendente.')
        return false
      end

      self.parent = conta_ancestry
      true
    end

    def conta_cancelada_nao_recebe_atividade
      conta_antes_atualizacao = Conta.find_by(id: self.id)

      if conta_antes_atualizacao.status == 'cancelado'
        errors.add(:conta, message: 'conta cancelada não sofre movimentações')
        return false
      end

      true
    end
end

app/controllers/conta_controller.rb
class ContaController < ApplicationController
  before_action :set_contum, only: [:show, :edit, :update, :destroy]

  # GET /conta
  # GET /conta.json
  def index
    @contum = Contum.all
  end

  # GET /conta/1
  # GET /conta/1.json
  def show
  end

  # GET /conta/new
  def new
    @contum = Contum.new
  end

  # GET /conta/1/edit
  def edit
  end

  # POST /conta
  # POST /conta.json
  def create
    @contum = Contum.new(contum_params)

    respond_to do |format|
      if @contum.save
        format.html { redirect_to @contum, notice: 'Contum was successfully created.' }
        format.json { render :show, status: :created, location: @contum }
      else
        format.html { render :new }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conta/1
  # PATCH/PUT /conta/1.json
  def update
    respond_to do |format|
      if @contum.update(contum_params)
        format.html { redirect_to @contum, notice: 'Contum was successfully updated.' }
        format.json { render :show, status: :ok, location: @contum }
      else
        format.html { render :edit }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conta/1
  # DELETE /conta/1.json
  def destroy
    @contum.destroy
    respond_to do |format|
      format.html { redirect_to conta_url, notice: 'Contum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contum
      @contum = Contum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contum_params
      params.require(:contum).permit(:nome, :saldo, :situacao, :pessoa_id, :pessoa_type, :ancestry)
    end
end

app/helpers/conta_helper.rb
module ContaHelper
end

app/views/conta/_form.html.erb
<%= form_for(@contum) do |f| %>
  <% if @contum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contum.errors.count, "error") %> prohibited this contum from being saved:</h2>

      <ul>
      <% @contum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldo %>
  </div>
  <div class="field">
    <%= f.label :situacao %><br>
    <%= f.number_field :situacao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conta/edit.html.erb
<h1>Editing Contum</h1>

<%= render 'form' %>

<%= link_to 'Show', @contum %> |
<%= link_to 'Back', conta_path %>

app/views/conta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conta</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Saldo</th>
      <th>Situacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conta.each do |contum| %>
      <tr>
        <td><%= contum.nome %></td>
        <td><%= contum.saldo %></td>
        <td><%= contum.situacao %></td>
        <td><%= link_to 'Show', contum %></td>
        <td><%= link_to 'Edit', edit_contum_path(contum) %></td>
        <td><%= link_to 'Destroy', contum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contum', new_contum_path %>

app/views/conta/new.html.erb
<h1>New Contum</h1>

<%= render 'form' %>

<%= link_to 'Back', conta_path %>

app/views/conta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contum.nome %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @contum.saldo %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @contum.situacao %>
</p>

<%= link_to 'Edit', edit_contum_path(@contum) %> |
<%= link_to 'Back', conta_path %>