config/routes.rb
Rails.application.routes.draw do
  resources :conta
  resources :transferencia
  resources :pessoa_juridicas
  resources :pessoa_fisicas

end

app/models/pessoa_juridica.rb
class PessoaJuridica < ActiveRecord::Base
      validates :cnpj, presence: true,
                   uniqueness: { case_insensitive: false },
                   numericality: { only_integer: true },
                   length: { is: 14 }

  validates :razao_social, presence: true,
                           uniqueness: true,
                           length: { in: 2..70 }

  validates :nome_fantasia, presence: true,
                            uniqueness: true,
                            length: { in: 2..70 }

  has_many :contas, as: :pessoa
end

app/controllers/pessoa_juridicas_controller.rb
class PessoaJuridicasController < ApplicationController
  before_action :set_pessoa_juridica, only: [:show, :edit, :update, :destroy]

  # GET /pessoa_juridicas
  # GET /pessoa_juridicas.json
  def index
    @pessoa_juridicas = PessoaJuridica.all
  end

  # GET /pessoa_juridicas/1
  # GET /pessoa_juridicas/1.json
  def show
  end

  # GET /pessoa_juridicas/new
  def new
    @pessoa_juridica = PessoaJuridica.new
  end

  # GET /pessoa_juridicas/1/edit
  def edit
  end

  # POST /pessoa_juridicas
  # POST /pessoa_juridicas.json
  def create
    @pessoa_juridica = PessoaJuridica.new(pessoa_juridica_params)

    respond_to do |format|
      if @pessoa_juridica.save
        format.html { redirect_to @pessoa_juridica, notice: 'Pessoa juridica was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa_juridica }
      else
        format.html { render :new }
        format.json { render json: @pessoa_juridica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoa_juridicas/1
  # PATCH/PUT /pessoa_juridicas/1.json
  def update
    respond_to do |format|
      if @pessoa_juridica.update(pessoa_juridica_params)
        format.html { redirect_to @pessoa_juridica, notice: 'Pessoa juridica was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa_juridica }
      else
        format.html { render :edit }
        format.json { render json: @pessoa_juridica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoa_juridicas/1
  # DELETE /pessoa_juridicas/1.json
  def destroy
    @pessoa_juridica.destroy
    respond_to do |format|
      format.html { redirect_to pessoa_juridicas_url, notice: 'Pessoa juridica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa_juridica
      @pessoa_juridica = PessoaJuridica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_juridica_params
      params.require(:pessoa_juridica).permit(:nome_fantasia, :razao_social, :cnpj)
    end
end

app/helpers/pessoa_juridicas_helper.rb
module PessoaJuridicasHelper
end

app/views/pessoa_juridicas/_form.html.erb
<%= form_for(@pessoa_juridica) do |f| %>
  <% if @pessoa_juridica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa_juridica.errors.count, "error") %> prohibited this pessoa_juridica from being saved:</h2>

      <ul>
      <% @pessoa_juridica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_fantasia %><br>
    <%= f.text_field :nome_fantasia %>
  </div>
  <div class="field">
    <%= f.label :razao_social %><br>
    <%= f.text_field :razao_social %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoa_juridicas/edit.html.erb
<h1>Editing Pessoa Juridica</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa_juridica %> |
<%= link_to 'Back', pessoa_juridicas_path %>

app/views/pessoa_juridicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pessoa Juridicas</h1>

<table>
  <thead>
    <tr>
      <th>Nome fantasia</th>
      <th>Razao social</th>
      <th>Cnpj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoa_juridicas.each do |pessoa_juridica| %>
      <tr>
        <td><%= pessoa_juridica.nome_fantasia %></td>
        <td><%= pessoa_juridica.razao_social %></td>
        <td><%= pessoa_juridica.cnpj %></td>
        <td><%= link_to 'Show', pessoa_juridica %></td>
        <td><%= link_to 'Edit', edit_pessoa_juridica_path(pessoa_juridica) %></td>
        <td><%= link_to 'Destroy', pessoa_juridica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa juridica', new_pessoa_juridica_path %>

app/views/pessoa_juridicas/new.html.erb
<h1>New Pessoa Juridica</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoa_juridicas_path %>

app/views/pessoa_juridicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome fantasia:</strong>
  <%= @pessoa_juridica.nome_fantasia %>
</p>

<p>
  <strong>Razao social:</strong>
  <%= @pessoa_juridica.razao_social %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @pessoa_juridica.cnpj %>
</p>

<%= link_to 'Edit', edit_pessoa_juridica_path(@pessoa_juridica) %> |
<%= link_to 'Back', pessoa_juridicas_path %>