config/routes.rb
Rails.application.routes.draw do
  resources :conta
  resources :transferencia
  resources :pessoa_juridicas
  resources :pessoa_fisicas

end

app/controllers/transferencia_controller.rb
class TransferenciaController < ApplicationController
  before_action :set_transferencium, only: [:show]

  # GET /transferencia
  # GET /transferencia.json
  def index
    @transferencia = Transferencium.all
  end

  # GET /transferencia/1
  # GET /transferencia/1.json
  def show
  end
  
  # POST /transferencia
  # POST /transferencia.json
  def create
    case params[:transferencium][:tipo]
          when 'carga' then @transferencium = TransacaoCarga.new(transferencium_params_carga)
          when 'transferencia' then @transferencium = TransacaoTransferencia.new(transferencium_params_transferencia)
          when 'estorno' then @transferencium = TransacaoEstorno.new(transferencium_params_estorno)
          else
            @transferencium = OpenStruct.new(errors: ({tipo: [{message: 'deve ser válido'}]}).to_json, efetuar: false)
    end

      if @transferencium.efetuar
          head 204, location: api_v1_transacao_url(@transferencium.id)
      else
          render json: @transferencium.errors, status: 422
      end
   end


  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_transferencium
      @transferencium = Transferencium.find(params[:id])
    end

      def get_conta
        @conta = Conta.find(params[:conta_id])
      end

      # Only allow a trusted parameter "white list" through.
      def transferencium_params
        params.require(:transferencium).permit(
            :tipo, :valor, :conta_debitada_id, :conta_creditada_id,
            :estorno, :condigo_estorno
        )
      end

      def transferencium_params_carga
        params.require(:transferencium).permit(:tipo, :valor, :conta_creditada_id)
      end

      def transferencium_params_transferencia
        params.require(:transferencium).permit(:tipo, :valor, :conta_debitada_id, :conta_creditada_id)
      end

      def transferencium_params_estorno
        params.require(:transferencium).permit(:tipo, :condigo_estorno)
      end
    end

app/helpers/transferencia_helper.rb
module TransferenciaHelper
    module Gerador
    def self.codigo_alphanumerico(params)
      return false unless validar_parametros_codigo_alphanumerico(params)

      date = DateTime.now.strftime('%Y%m%d%H%M%S%L').to_s
      conta_origem_id = params[:conta_debitada_id].to_s
      conta_destino_id = params[:conta_creditada_id].to_s
      tipo = params[:tipo].to_s

      valor = date + conta_debitada_id + tipo + conta_creditada_id
      Digest::MD5.hexdigest(valor)
    end

    private

      def self.validar_parametros_codigo_alphanumerico(params)
        return false unless params[:conta_debitada_id].is_a?(Integer)
        return false unless params[:conta_creditada_id].is_a?(Integer) || params[:conta_creditada_id].blank?

        return false unless Transferencia.tipos.keys.include?(params[:tipo])
        true
      end
  end
end

app/views/transferencia/_form.html.erb
<%= form_for(@transferencium) do |f| %>
  <% if @transferencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transferencium.errors.count, "error") %> prohibited this transferencium from being saved:</h2>

      <ul>
      <% @transferencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo_alfa_numerico %><br>
    <%= f.text_field :codigo_alfa_numerico %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.number_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :estorno %><br>
    <%= f.check_box :estorno %>
  </div>
  <div class="field">
    <%= f.label :codigo_estorno %><br>
    <%= f.text_field :codigo_estorno %>
  </div>
  <div class="field">
    <%= f.label :conta_debitada_saldo %><br>
    <%= f.text_field :conta_debitada_saldo %>
  </div>
  <div class="field">
    <%= f.label :conta_creditada_saldo %><br>
    <%= f.text_field :conta_creditada_saldo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transferencia/edit.html.erb
<h1>Editing Transferencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @transferencium %> |
<%= link_to 'Back', transferencia_path %>

app/views/transferencia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transferencia</h1>

<table>
  <thead>
    <tr>
      <th>Codigo alfa numerico</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th>Estorno</th>
      <th>Codigo estorno</th>
      <th>Conta debitada saldo</th>
      <th>Conta creditada saldo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transferencia.each do |transferencium| %>
      <tr>
        <td><%= transferencium.codigo_alfa_numerico %></td>
        <td><%= transferencium.tipo %></td>
        <td><%= transferencium.valor %></td>
        <td><%= transferencium.estorno %></td>
        <td><%= transferencium.codigo_estorno %></td>
        <td><%= transferencium.conta_debitada_saldo %></td>
        <td><%= transferencium.conta_creditada_saldo %></td>
        <td><%= link_to 'Show', transferencium %></td>
        <td><%= link_to 'Edit', edit_transferencium_path(transferencium) %></td>
        <td><%= link_to 'Destroy', transferencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transferencium', new_transferencium_path %>

app/views/transferencia/new.html.erb
<h1>New Transferencium</h1>

<%= render 'form' %>

<%= link_to 'Back', transferencia_path %>

app/views/transferencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo alfa numerico:</strong>
  <%= @transferencium.codigo_alfa_numerico %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @transferencium.tipo %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transferencium.valor %>
</p>

<p>
  <strong>Estorno:</strong>
  <%= @transferencium.estorno %>
</p>

<p>
  <strong>Codigo estorno:</strong>
  <%= @transferencium.codigo_estorno %>
</p>

<p>
  <strong>Conta debitada saldo:</strong>
  <%= @transferencium.conta_debitada_saldo %>
</p>

<p>
  <strong>Conta creditada saldo:</strong>
  <%= @transferencium.conta_creditada_saldo %>
</p>

<%= link_to 'Edit', edit_transferencium_path(@transferencium) %> |
<%= link_to 'Back', transferencia_path %>